version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recarga-database
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - default

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - default

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks: 
      - default
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  recargabalance:
    build:
      context: ./recarga-balance
      dockerfile: Dockerfile
    ports:
      - "8081:8080" 
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - kafka
    networks:
      - default

  recargatransactions:
    build:
      context: ./recarga-transactions
      dockerfile: Dockerfile
    ports:
      - "8082:8080" 
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - kafka
    networks:
      - default

  recargatstatements:
    build:
      context: ./recarga-statements
      dockerfile: Dockerfile
    ports:
      - "8083:8080" 
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - kafka
    networks:
      - default

networks:
  default:
    driver: bridge